### ISSUE TITLE
apt-get update -y  under line:3 of Dockerfile

### ISSUE THREAD

**Issue by ajeetraina** [taivokasper/docker-gource#2]
Couple of time I have used Dockerfile to build the gource image and I faced issue with initial package installation. It would be better to add -y with apt-get update.

**Comment by taivokasper** [comment]
I have fixed this issue, issue where you might have had a container where 'apt-get update' was already done a while back and fixed the ubuntu version.

Also published it to [Docker Hub](https://hub.docker.com/r/taivokasper/docker-gource/).
